version: 1.0.{build}
skip_tags: true
os: Visual Studio 2017 RC
configuration: Release
environment:
  VisualStudioVersion: 15.0
  GeneratePInvokesTxt: true
  TreatWarningsAsErrors: true
before_build:
- ps: >-
    .\build.ps1 -Restore

    #$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
- ps: .\build.ps1 -Build
test_script:
- ps: .\build.ps1 -Test -NoParallelTests
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
- path: bin\**\*.pinvokes.txt
  name: PInvoke method coverage
- path: bin\**\*.exports.txt
  name: Exported methods
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/c4d61fc5002e9a62a22f
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
